export type BlogLocale = 'en' | 'es' | 'ar' | 'ja' | 'pt' | 'fr' | 'de' | 'tr' | 'id' | 'hi';

export type KeywordCategory = 'twitter' | 'tiktok' | 'telegram' | 'comparison';

export type KeywordArticle = {
  slug: string;
  category: KeywordCategory;
  keyword: {
    en: string;
    es: string;
    ar: string;
    ja: string;
    pt: string;
    fr: string;
    de: string;
    tr: string;
    id: string;
    hi: string;
  };
  toolPath: string;
  supportPath: string;
};

const baseArticles: Array<{
  slug: string;
  category: KeywordCategory;
  en: string;
  toolPath: string;
  supportPath: string;
}> = [
  { slug: 'how-to-download-twitter-videos', category: 'twitter', en: 'how to download twitter videos', toolPath: '/download-twitter-video', supportPath: '/solution/twitter-video-downloader-not-working' },
  { slug: 'twitter-video-downloader-online-free', category: 'twitter', en: 'twitter video downloader online free', toolPath: '/download-twitter-video', supportPath: '/solution/twitter-video-downloader-not-working' },
  { slug: 'twitter-video-download-iphone', category: 'twitter', en: 'twitter video download iphone', toolPath: '/download-twitter-video', supportPath: '/solution/twitter-video-downloader-not-working' },
  { slug: 'twitter-video-save-method-ja', category: 'twitter', en: 'twitter 動画 保存 方法', toolPath: '/download-twitter-video', supportPath: '/solution/twitter-video-downloader-not-working' },
  { slug: 'twitter-video-save-not-working-ja', category: 'twitter', en: 'twitter 動画 保存 できない', toolPath: '/download-twitter-video', supportPath: '/solution/twitter-video-downloader-not-working' },
  { slug: 'twitter-video-download-android', category: 'twitter', en: 'twitter video download android', toolPath: '/download-twitter-video', supportPath: '/solution/twitter-video-downloader-not-working' },
  { slug: 'twitter-gif-download', category: 'twitter', en: 'twitter gif download', toolPath: '/download-twitter-video', supportPath: '/solution/twitter-video-downloader-not-working' },
  { slug: 'twitter-video-downloader-safe', category: 'twitter', en: 'twitter video downloader safe', toolPath: '/download-twitter-video', supportPath: '/legal/privacy' },
  { slug: 'twitter-video-download-no-watermark', category: 'twitter', en: 'twitter video download no watermark', toolPath: '/download-twitter-video', supportPath: '/legal/terms' },
  { slug: 'twitter-video-download-mp4', category: 'twitter', en: 'twitter video download mp4', toolPath: '/download-twitter-video', supportPath: '/solution/twitter-video-downloader-not-working' },
  { slug: 'twitter-video-download-chrome', category: 'twitter', en: 'twitter video download chrome', toolPath: '/download-twitter-video', supportPath: '/solution/twitter-video-downloader-not-working' },
  { slug: 'twitter-save-visible-ja', category: 'twitter', en: 'twitter 保存 ばれる？', toolPath: '/download-twitter-video', supportPath: '/legal/privacy' },
  { slug: 'twitter-video-download-private-account', category: 'twitter', en: 'twitter video download private account', toolPath: '/download-twitter-video', supportPath: '/legal/terms' },
  { slug: 'twitter-video-download-without-login', category: 'twitter', en: 'twitter video download without login', toolPath: '/download-twitter-video', supportPath: '/legal/terms' },
  { slug: 'twitter-video-downloader-2026', category: 'twitter', en: 'twitter video downloader 2026', toolPath: '/download-twitter-video', supportPath: '/twitter-trending-videos' },
  { slug: 'tiktok-video-download-no-watermark', category: 'tiktok', en: 'tiktok video download no watermark', toolPath: '/download-tiktok-video', supportPath: '/solution/extractor-temporary-limited' },
  { slug: 'tiktok-downloader-without-watermark-online', category: 'tiktok', en: 'tiktok downloader without watermark online', toolPath: '/download-tiktok-video', supportPath: '/solution/extractor-temporary-limited' },
  { slug: 'tiktok-video-save-method-ja', category: 'tiktok', en: 'tiktok 動画 保存 方法', toolPath: '/download-tiktok-video', supportPath: '/solution/extractor-temporary-limited' },
  { slug: 'tiktok-video-save-not-working-ja', category: 'tiktok', en: 'tiktok 動画 保存 できない', toolPath: '/download-tiktok-video', supportPath: '/solution/extractor-temporary-limited' },
  { slug: 'download-tiktok-video-hd', category: 'tiktok', en: 'download tiktok video hd', toolPath: '/download-tiktok-video', supportPath: '/solution/extractor-temporary-limited' },
  { slug: 'tiktok-download-mp4', category: 'tiktok', en: 'tiktok download mp4', toolPath: '/download-tiktok-video', supportPath: '/solution/extractor-temporary-limited' },
  { slug: 'save-tiktok-video-iphone', category: 'tiktok', en: 'save tiktok video iphone', toolPath: '/download-tiktok-video', supportPath: '/solution/extractor-temporary-limited' },
  { slug: 'tiktok-video-download-android', category: 'tiktok', en: 'tiktok video download android', toolPath: '/download-tiktok-video', supportPath: '/solution/extractor-temporary-limited' },
  { slug: 'tiktok-downloader-safe', category: 'tiktok', en: 'tiktok downloader safe', toolPath: '/download-tiktok-video', supportPath: '/legal/privacy' },
  { slug: 'tiktok-video-downloader-free', category: 'tiktok', en: 'tiktok video downloader free', toolPath: '/download-tiktok-video', supportPath: '/tiktok-trending-videos' },
  { slug: 'tiktok-video-download-private', category: 'tiktok', en: 'tiktok video download private', toolPath: '/download-tiktok-video', supportPath: '/legal/terms' },
  { slug: 'tiktok-save-visible-ja', category: 'tiktok', en: 'tiktok 保存 バレる？', toolPath: '/download-tiktok-video', supportPath: '/legal/privacy' },
  { slug: 'how-to-save-tiktok-without-watermark', category: 'tiktok', en: 'how to save tiktok without watermark', toolPath: '/download-tiktok-video', supportPath: '/solution/extractor-temporary-limited' },
  { slug: 'tiktok-video-downloader-2026', category: 'tiktok', en: 'tiktok video downloader 2026', toolPath: '/download-tiktok-video', supportPath: '/tiktok-trending-videos' },
  { slug: 'tiktok-video-link-download', category: 'tiktok', en: 'tiktok video link download', toolPath: '/download-tiktok-video', supportPath: '/solution/extractor-temporary-limited' },
  { slug: 'telegram-video-download', category: 'telegram', en: 'telegram video download', toolPath: '/download-telegram-video', supportPath: '/solution/telegram-video-downloader-not-working' },
  { slug: 'telegram-video-downloader-online', category: 'telegram', en: 'telegram video downloader online', toolPath: '/download-telegram-video', supportPath: '/solution/telegram-video-downloader-not-working' },
  { slug: 'telegram-video-save-method-ja', category: 'telegram', en: 'telegram 動画 保存 方法', toolPath: '/download-telegram-video', supportPath: '/solution/telegram-video-downloader-not-working' },
  { slug: 'telegram-video-download-pc-ja', category: 'telegram', en: 'telegram 動画 ダウンロード pc', toolPath: '/download-telegram-video', supportPath: '/solution/telegram-video-downloader-not-working' },
  { slug: 'telegram-video-download-iphone', category: 'telegram', en: 'telegram video download iphone', toolPath: '/download-telegram-video', supportPath: '/solution/telegram-video-downloader-not-working' },
  { slug: 'telegram-video-download-android', category: 'telegram', en: 'telegram video download android', toolPath: '/download-telegram-video', supportPath: '/solution/telegram-video-downloader-not-working' },
  { slug: 'telegram-private-video-download', category: 'telegram', en: 'telegram private video download', toolPath: '/download-telegram-video', supportPath: '/legal/terms' },
  { slug: 'telegram-video-download-link', category: 'telegram', en: 'telegram video download link', toolPath: '/download-telegram-video', supportPath: '/solution/telegram-video-downloader-not-working' },
  { slug: 'telegram-save-visible-ja', category: 'telegram', en: 'telegram 保存 バレる？', toolPath: '/download-telegram-video', supportPath: '/legal/privacy' },
  { slug: 'telegram-video-download-bot-safe', category: 'telegram', en: 'telegram video download bot safe', toolPath: '/download-telegram-video', supportPath: '/legal/privacy' },
  { slug: 'best-twitter-video-downloader-2026', category: 'comparison', en: 'best twitter video downloader 2026', toolPath: '/download-twitter-video', supportPath: '/twitter-trending-videos' },
  { slug: 'best-tiktok-downloader-without-watermark', category: 'comparison', en: 'best tiktok downloader without watermark', toolPath: '/download-tiktok-video', supportPath: '/tiktok-trending-videos' },
  { slug: 'safest-video-downloader-sites', category: 'comparison', en: 'safest video downloader sites', toolPath: '/download-twitter-video', supportPath: '/legal/privacy' },
  { slug: 'twitter-video-downloader-not-working', category: 'comparison', en: 'twitter video downloader not working', toolPath: '/download-twitter-video', supportPath: '/solution/twitter-video-downloader-not-working' },
  { slug: 'tiktok-downloader-not-working', category: 'comparison', en: 'tiktok downloader not working', toolPath: '/download-tiktok-video', supportPath: '/solution/extractor-temporary-limited' },
  { slug: 'telegram-video-download-not-working', category: 'comparison', en: 'telegram video download not working', toolPath: '/download-telegram-video', supportPath: '/solution/telegram-video-downloader-not-working' },
  { slug: 'is-video-downloader-legal', category: 'comparison', en: 'is video downloader legal', toolPath: '/legal/terms', supportPath: '/legal/dmca' },
  { slug: 'video-downloader-safe-or-not', category: 'comparison', en: 'video downloader safe or not', toolPath: '/legal/privacy', supportPath: '/status' },
  { slug: 'free-video-downloader-online-comparison', category: 'comparison', en: 'free video downloader online comparison', toolPath: '/download-twitter-video', supportPath: '/faq' },
  { slug: 'top-5-video-downloader-tools', category: 'comparison', en: 'top 5 video downloader tools', toolPath: '/download-twitter-video', supportPath: '/faq' },
];

function localizeKeyword(keywordEn: string, locale: BlogLocale): string {
  if (locale === 'en') return keywordEn;
  if (locale === 'ja') return keywordEn; // Keep as is, some already have ja
  if (locale === 'fr' || locale === 'de' || locale === 'tr') return keywordEn;

  const mapEs: Array<[RegExp, string]> = [
    [/video downloader/gi, 'descargador de videos'],
    [/video download/gi, 'descargar video'],
    [/download/gi, 'descargar'],
    [/how to/gi, 'como'],
    [/without/gi, 'sin'],
    [/safe/gi, 'seguro'],
    [/not working/gi, 'no funciona'],
    [/private account/gi, 'cuenta privada'],
    [/without login/gi, 'sin iniciar sesion'],
    [/best/gi, 'mejor'],
    [/comparison/gi, 'comparacion'],
    [/link/gi, 'enlace'],
    [/twitter/gi, 'twitter'],
    [/tiktok/gi, 'tiktok'],
    [/telegram/gi, 'telegram'],
  ];

  const mapAr: Array<[RegExp, string]> = [
    [/video downloader/gi, 'تنزيل الفيديو'],
    [/video download/gi, 'تنزيل فيديو'],
    [/download/gi, 'تنزيل'],
    [/how to/gi, 'كيفية'],
    [/without/gi, 'بدون'],
    [/safe/gi, 'آمن'],
    [/not working/gi, 'لا يعمل'],
    [/private account/gi, 'حساب خاص'],
    [/without login/gi, 'بدون تسجيل دخول'],
    [/best/gi, 'أفضل'],
    [/comparison/gi, 'مقارنة'],
    [/link/gi, 'رابط'],
    [/twitter/gi, 'تويتر'],
    [/tiktok/gi, 'تيك توك'],
    [/telegram/gi, 'تيليجرام'],
  ];

  let out = keywordEn;
  const mapper = locale === 'es' ? mapEs : mapAr;
  for (const [p, r] of mapper) out = out.replace(p, r);
  return out;
}


const keywordFrBySlug: Record<string, string> = {
  'how-to-download-twitter-videos': 'comment télécharger des vidéos Twitter',
  'twitter-video-downloader-online-free': 'téléchargeur de vidéos Twitter gratuit en ligne',
  'twitter-video-download-iphone': 'comment télécharger une vidéo Twitter sur iPhone',
  'twitter-video-save-method-ja': 'comment enregistrer des vidéos Twitter',
  'twitter-video-save-not-working-ja': 'la vidéo Twitter ne se télécharge pas',
  'twitter-video-download-android': 'comment télécharger une vidéo Twitter sur Android',
  'twitter-gif-download': 'comment télécharger un GIF Twitter',
  'twitter-video-downloader-safe': 'un téléchargeur de vidéos Twitter est-il sûr ?',
  'twitter-video-download-no-watermark': 'télécharger une vidéo Twitter sans filigrane',
  'twitter-video-download-mp4': 'télécharger une vidéo Twitter en MP4',
  'twitter-video-download-chrome': 'télécharger une vidéo Twitter sur Chrome',
  'twitter-save-visible-ja': 'enregistrer une vidéo Twitter envoie-t-il une notification ?',
  'twitter-video-download-private-account': 'télécharger une vidéo Twitter depuis un compte privé',
  'twitter-video-download-without-login': 'télécharger une vidéo Twitter sans connexion',
  'twitter-video-downloader-2026': 'téléchargeur de vidéos Twitter 2026',
  'tiktok-video-download-no-watermark': 'télécharger une vidéo TikTok sans filigrane',
  'tiktok-downloader-without-watermark-online': 'téléchargeur TikTok en ligne sans filigrane',
  'tiktok-video-save-method-ja': 'comment enregistrer des vidéos TikTok',
  'tiktok-video-save-not-working-ja': 'la vidéo TikTok ne se télécharge pas',
  'download-tiktok-video-hd': 'télécharger une vidéo TikTok en HD',
  'tiktok-download-mp4': 'télécharger une vidéo TikTok en MP4',
  'save-tiktok-video-iphone': 'comment enregistrer une vidéo TikTok sur iPhone',
  'tiktok-video-download-android': 'comment télécharger une vidéo TikTok sur Android',
  'tiktok-downloader-safe': 'un téléchargeur TikTok est-il sûr ?',
  'tiktok-video-downloader-free': 'téléchargeur de vidéos TikTok gratuit',
  'tiktok-video-download-private': 'télécharger une vidéo TikTok privée',
  'tiktok-save-visible-ja': 'enregistrer une vidéo TikTok envoie-t-il une notification ?',
  'how-to-save-tiktok-without-watermark': 'comment enregistrer une vidéo TikTok sans filigrane',
  'tiktok-video-downloader-2026': 'téléchargeur de vidéos TikTok 2026',
  'tiktok-video-link-download': 'télécharger une vidéo TikTok par lien',
  'telegram-video-download': 'télécharger une vidéo Telegram',
  'telegram-video-downloader-online': 'téléchargeur de vidéos Telegram en ligne',
  'telegram-video-save-method-ja': 'comment enregistrer des vidéos Telegram',
  'telegram-video-download-pc-ja': 'télécharger une vidéo Telegram sur PC',
  'telegram-video-download-iphone': 'télécharger une vidéo Telegram sur iPhone',
  'telegram-video-download-android': 'télécharger une vidéo Telegram sur Android',
  'telegram-private-video-download': 'télécharger une vidéo Telegram privée',
  'telegram-video-download-link': 'télécharger une vidéo Telegram par lien',
  'telegram-save-visible-ja': 'enregistrer une vidéo Telegram envoie-t-il une notification ?',
  'telegram-video-download-bot-safe': 'est-il sûr d’utiliser un bot pour télécharger une vidéo Telegram ?',
  'best-twitter-video-downloader-2026': 'meilleur téléchargeur de vidéos Twitter 2026',
  'best-tiktok-downloader-without-watermark': 'meilleur téléchargeur TikTok sans filigrane',
  'safest-video-downloader-sites': 'sites de téléchargement de vidéos les plus sûrs',
  'twitter-video-downloader-not-working': 'le téléchargement de vidéos Twitter ne fonctionne pas',
  'tiktok-downloader-not-working': 'le téléchargement TikTok ne fonctionne pas',
  'telegram-video-download-not-working': 'le téléchargement de vidéos Telegram ne fonctionne pas',
  'is-video-downloader-legal': 'utiliser un téléchargeur de vidéos est-il légal ?',
  'video-downloader-safe-or-not': 'un téléchargeur de vidéos est-il sûr ou non ?',
  'free-video-downloader-online-comparison': 'comparatif des téléchargeurs de vidéos gratuits en ligne',
  'top-5-video-downloader-tools': 'top 5 des outils de téléchargement vidéo',
};


const keywordDeBySlug: Record<string, string> = {
  'how-to-download-twitter-videos': 'wie man Videos von Twitter herunterlädt',
  'twitter-video-downloader-online-free': 'kostenloser Twitter-Video-Downloader online',
  'twitter-video-download-iphone': 'Twitter-Video auf dem iPhone herunterladen',
  'twitter-video-save-method-ja': 'Twitter-Videos speichern',
  'twitter-video-save-not-working-ja': 'Twitter-Video lässt sich nicht speichern',
  'twitter-video-download-android': 'Twitter-Video auf Android herunterladen',
  'twitter-gif-download': 'Twitter-GIF herunterladen',
  'twitter-video-downloader-safe': 'ist ein Twitter-Video-Downloader sicher?',
  'twitter-video-download-no-watermark': 'Twitter-Video ohne Wasserzeichen herunterladen',
  'twitter-video-download-mp4': 'Twitter-Video als MP4 herunterladen',
  'twitter-video-download-chrome': 'Twitter-Video in Chrome herunterladen',
  'twitter-save-visible-ja': 'merkt jemand, wenn ich ein Twitter-Video speichere?',
  'twitter-video-download-private-account': 'Twitter-Video von privatem Konto herunterladen',
  'twitter-video-download-without-login': 'Twitter-Video ohne Login herunterladen',
  'twitter-video-downloader-2026': 'Twitter-Video-Downloader 2026',
  'tiktok-video-download-no-watermark': 'TikTok-Video ohne Wasserzeichen herunterladen',
  'tiktok-downloader-without-watermark-online': 'TikTok-Downloader online ohne Wasserzeichen',
  'tiktok-video-save-method-ja': 'TikTok-Videos speichern',
  'tiktok-video-save-not-working-ja': 'TikTok-Video lässt sich nicht speichern',
  'download-tiktok-video-hd': 'TikTok-Video in HD herunterladen',
  'tiktok-download-mp4': 'TikTok-Video als MP4 herunterladen',
  'save-tiktok-video-iphone': 'TikTok-Video auf dem iPhone speichern',
  'tiktok-video-download-android': 'TikTok-Video auf Android herunterladen',
  'tiktok-downloader-safe': 'ist ein TikTok-Downloader sicher?',
  'tiktok-video-downloader-free': 'kostenloser TikTok-Video-Downloader',
  'tiktok-video-download-private': 'privates TikTok-Video herunterladen',
  'tiktok-save-visible-ja': 'merkt jemand, wenn ich ein TikTok-Video speichere?',
  'how-to-save-tiktok-without-watermark': 'wie man TikTok-Videos ohne Wasserzeichen speichert',
  'tiktok-video-downloader-2026': 'TikTok-Video-Downloader 2026',
  'tiktok-video-link-download': 'TikTok-Video per Link herunterladen',
  'telegram-video-download': 'Telegram-Video herunterladen',
  'telegram-video-downloader-online': 'Telegram-Video-Downloader online',
  'telegram-video-save-method-ja': 'Telegram-Videos speichern',
  'telegram-video-download-pc-ja': 'Telegram-Video auf dem PC herunterladen',
  'telegram-video-download-iphone': 'Telegram-Video auf dem iPhone herunterladen',
  'telegram-video-download-android': 'Telegram-Video auf Android herunterladen',
  'telegram-private-video-download': 'privates Telegram-Video herunterladen',
  'telegram-video-download-link': 'Telegram-Video per Link herunterladen',
  'telegram-save-visible-ja': 'merkt jemand, wenn ich ein Telegram-Video speichere?',
  'telegram-video-download-bot-safe': 'ist ein Telegram-Bot zum Herunterladen von Videos sicher?',
  'best-twitter-video-downloader-2026': 'bester Twitter-Video-Downloader 2026',
  'best-tiktok-downloader-without-watermark': 'bester TikTok-Downloader ohne Wasserzeichen',
  'safest-video-downloader-sites': 'sicherste Video-Downloader-Seiten',
  'twitter-video-downloader-not-working': 'Twitter-Video-Download funktioniert nicht',
  'tiktok-downloader-not-working': 'TikTok-Downloader funktioniert nicht',
  'telegram-video-download-not-working': 'Telegram-Video-Download funktioniert nicht',
  'is-video-downloader-legal': 'ist ein Video-Downloader legal?',
  'video-downloader-safe-or-not': 'ist ein Video-Downloader sicher oder nicht?',
  'free-video-downloader-online-comparison': 'Vergleich kostenloser Online-Video-Downloader',
  'top-5-video-downloader-tools': 'Top 5 Video-Downloader-Tools',
};


const keywordTrBySlug: Record<string, string> = {
  'how-to-download-twitter-videos': 'Twitter videoları nasıl indirilir',
  'twitter-video-downloader-online-free': 'ücretsiz çevrim içi Twitter video indirici',
  'twitter-video-download-iphone': 'iPhone’da Twitter videosu nasıl indirilir',
  'twitter-video-save-method-ja': 'Twitter videoları kaydetme yöntemi',
  'twitter-video-save-not-working-ja': 'Twitter videosu kaydedilmiyor',
  'twitter-video-download-android': 'Android’de Twitter videosu nasıl indirilir',
  'twitter-gif-download': 'Twitter GIF nasıl indirilir',
  'twitter-video-downloader-safe': 'Twitter video indirici güvenli mi?',
  'twitter-video-download-no-watermark': 'filigransız Twitter videosu indirme',
  'twitter-video-download-mp4': 'Twitter videosunu MP4 olarak indirme',
  'twitter-video-download-chrome': 'Chrome’da Twitter videosu indirme',
  'twitter-save-visible-ja': 'Twitter videosu kaydedildiğinde karşı taraf anlar mı?',
  'twitter-video-download-private-account': 'özel hesaptan Twitter videosu indirme',
  'twitter-video-download-without-login': 'giriş yapmadan Twitter videosu nasıl indirilir',
  'twitter-video-downloader-2026': 'Twitter video indirici 2026',
  'tiktok-video-download-no-watermark': 'filigransız TikTok videosu indirme',
  'tiktok-downloader-without-watermark-online': 'çevrim içi filigransız TikTok indirici',
  'tiktok-video-save-method-ja': 'TikTok videoları kaydetme yöntemi',
  'tiktok-video-save-not-working-ja': 'TikTok videosu neden kaydedilmiyor?',
  'download-tiktok-video-hd': 'HD TikTok videosu indirme',
  'tiktok-download-mp4': 'TikTok videosunu MP4 olarak indirme',
  'save-tiktok-video-iphone': 'iPhone’da TikTok videosu nasıl kaydedilir',
  'tiktok-video-download-android': 'Android’de TikTok videosu nasıl indirilir',
  'tiktok-downloader-safe': 'TikTok indirici güvenli mi?',
  'tiktok-video-downloader-free': 'ücretsiz TikTok video indirici',
  'tiktok-video-download-private': 'özel TikTok videosu indirme',
  'tiktok-save-visible-ja': 'TikTok videosu kaydedildiğinde karşı taraf anlar mı?',
  'how-to-save-tiktok-without-watermark': 'filigransız TikTok videosu nasıl kaydedilir',
  'tiktok-video-downloader-2026': 'TikTok video indirici 2026',
  'tiktok-video-link-download': 'link ile TikTok videosu indirme',
  'telegram-video-download': 'Telegram videosu nasıl indirilir',
  'telegram-video-downloader-online': 'çevrim içi Telegram video indirici aracı',
  'telegram-video-save-method-ja': 'Telegram videoları kaydetme yöntemi',
  'telegram-video-download-pc-ja': 'PC’de Telegram videosu nasıl indirilir',
  'telegram-video-download-iphone': 'iPhone’da Telegram videosu nasıl indirilir',
  'telegram-video-download-android': 'Android’de Telegram videosu nasıl indirilir',
  'telegram-private-video-download': 'özel Telegram videosu indirme',
  'telegram-video-download-link': 'link ile Telegram videosu indirme',
  'telegram-save-visible-ja': 'Telegram videosu kaydedildiğinde karşı taraf anlar mı?',
  'telegram-video-download-bot-safe': 'Telegram video indirme botu güvenli mi?',
  'best-twitter-video-downloader-2026': 'en iyi Twitter video indirici 2026',
  'best-tiktok-downloader-without-watermark': 'en iyi filigransız TikTok indirici',
  'safest-video-downloader-sites': 'en güvenli video indirme siteleri',
  'twitter-video-downloader-not-working': 'Twitter video indirici çalışmıyor',
  'tiktok-downloader-not-working': 'TikTok indirici çalışmıyor',
  'telegram-video-download-not-working': 'Telegram video indirme çalışmıyor',
  'is-video-downloader-legal': 'video indirici kullanmak yasal mı?',
  'video-downloader-safe-or-not': 'video indirici güvenli mi?',
  'free-video-downloader-online-comparison': 'ücretsiz çevrim içi video indirici karşılaştırması',
  'top-5-video-downloader-tools': 'en iyi 5 video indirme aracı',
};


const keywordIdBySlug: Record<string, string> = {
  'how-to-download-twitter-videos': 'cara download video Twitter',
  'twitter-video-downloader-online-free': 'pengunduh video Twitter online gratis',
  'twitter-video-download-iphone': 'cara download video Twitter di iPhone',
  'twitter-video-save-method-ja': 'cara menyimpan video Twitter',
  'twitter-video-save-not-working-ja': 'kenapa video Twitter tidak bisa disimpan?',
  'twitter-video-download-android': 'cara download video Twitter di Android',
  'twitter-gif-download': 'cara download GIF Twitter',
  'twitter-video-downloader-safe': 'apakah pengunduh video Twitter aman?',
  'twitter-video-download-no-watermark': 'cara download video Twitter tanpa watermark',
  'twitter-video-download-mp4': 'cara download video Twitter dalam format MP4',
  'twitter-video-download-chrome': 'cara download video Twitter di Chrome',
  'twitter-save-visible-ja': 'apakah orang lain tahu saat video Twitter disimpan?',
  'twitter-video-download-private-account': 'cara download video Twitter dari akun privat',
  'twitter-video-download-without-login': 'cara download video Twitter tanpa login',
  'twitter-video-downloader-2026': 'pengunduh video Twitter 2026',
  'tiktok-video-download-no-watermark': 'cara download video TikTok tanpa watermark',
  'tiktok-downloader-without-watermark-online': 'pengunduh TikTok tanpa watermark online',
  'tiktok-video-save-method-ja': 'cara menyimpan video TikTok',
  'tiktok-video-save-not-working-ja': 'kenapa video TikTok tidak bisa disimpan?',
  'download-tiktok-video-hd': 'cara download video TikTok HD',
  'tiktok-download-mp4': 'cara download video TikTok dalam format MP4',
  'save-tiktok-video-iphone': 'cara menyimpan video TikTok di iPhone',
  'tiktok-video-download-android': 'cara download video TikTok di Android',
  'tiktok-downloader-safe': 'apakah pengunduh TikTok aman?',
  'tiktok-video-downloader-free': 'pengunduh video TikTok gratis',
  'tiktok-video-download-private': 'cara download video TikTok privat',
  'tiktok-save-visible-ja': 'apakah orang lain tahu saat video TikTok disimpan?',
  'how-to-save-tiktok-without-watermark': 'cara menyimpan video TikTok tanpa watermark',
  'tiktok-video-downloader-2026': 'pengunduh video TikTok 2026',
  'tiktok-video-link-download': 'download video TikTok lewat link',
  'telegram-video-download': 'cara download video Telegram',
  'telegram-video-downloader-online': 'pengunduh video Telegram online terbaik',
  'telegram-video-save-method-ja': 'cara menyimpan video Telegram',
  'telegram-video-download-pc-ja': 'cara download video Telegram di PC',
  'telegram-video-download-iphone': 'cara download video Telegram di iPhone',
  'telegram-video-download-android': 'cara download video Telegram di Android',
  'telegram-private-video-download': 'cara download video Telegram privat',
  'telegram-video-download-link': 'cara download video Telegram dari link',
  'telegram-save-visible-ja': 'apakah orang lain tahu saat video Telegram disimpan?',
  'telegram-video-download-bot-safe': 'apakah bot download video Telegram aman?',
  'best-twitter-video-downloader-2026': 'pengunduh video Twitter terbaik tahun 2026',
  'best-tiktok-downloader-without-watermark': 'pengunduh TikTok tanpa watermark terbaik',
  'safest-video-downloader-sites': 'situs pengunduh video paling aman',
  'twitter-video-downloader-not-working': 'pengunduh video Twitter tidak berfungsi',
  'tiktok-downloader-not-working': 'pengunduh TikTok tidak berfungsi',
  'telegram-video-download-not-working': 'download video Telegram tidak berfungsi',
  'is-video-downloader-legal': 'apakah penggunaan pengunduh video legal?',
  'video-downloader-safe-or-not': 'apakah pengunduh video benar-benar aman?',
  'free-video-downloader-online-comparison': 'perbandingan pengunduh video online gratis',
  'top-5-video-downloader-tools': '5 alat pengunduh video terbaik',
};


const keywordHiBySlug: Record<string, string> = {
  'how-to-download-twitter-videos': 'Twitter वीडियो कैसे डाउनलोड करें',
  'twitter-video-downloader-online-free': 'मुफ्त ऑनलाइन Twitter वीडियो डाउनलोडर',
  'twitter-video-download-iphone': 'iPhone पर Twitter वीडियो कैसे डाउनलोड करें',
  'twitter-video-save-method-ja': 'Twitter वीडियो सेव करने का तरीका',
  'twitter-video-save-not-working-ja': 'Twitter वीडियो सेव क्यों नहीं हो रहा?',
  'twitter-video-download-android': 'Android पर Twitter वीडियो कैसे डाउनलोड करें',
  'twitter-gif-download': 'Twitter GIF कैसे डाउनलोड करें',
  'twitter-video-downloader-safe': 'क्या Twitter वीडियो डाउनलोडर सुरक्षित है?',
  'twitter-video-download-no-watermark': 'बिना वॉटरमार्क Twitter वीडियो कैसे डाउनलोड करें',
  'twitter-video-download-mp4': 'Twitter वीडियो MP4 में कैसे डाउनलोड करें',
  'twitter-video-download-chrome': 'Chrome में Twitter वीडियो कैसे डाउनलोड करें',
  'twitter-save-visible-ja': 'क्या Twitter वीडियो सेव करने पर दूसरे को पता चलता है?',
  'twitter-video-download-private-account': 'प्राइवेट अकाउंट से Twitter वीडियो कैसे डाउनलोड करें',
  'twitter-video-download-without-login': 'बिना लॉगिन Twitter वीडियो कैसे डाउनलोड करें',
  'twitter-video-downloader-2026': 'Twitter वीडियो डाउनलोडर 2026',
  'tiktok-video-download-no-watermark': 'बिना वॉटरमार्क TikTok वीडियो कैसे डाउनलोड करें',
  'tiktok-downloader-without-watermark-online': 'ऑनलाइन बिना वॉटरमार्क TikTok डाउनलोडर',
  'tiktok-video-save-method-ja': 'TikTok वीडियो सेव करने का तरीका',
  'tiktok-video-save-not-working-ja': 'TikTok वीडियो सेव क्यों नहीं हो रहा?',
  'download-tiktok-video-hd': 'HD TikTok वीडियो कैसे डाउनलोड करें',
  'tiktok-download-mp4': 'TikTok वीडियो MP4 में कैसे डाउनलोड करें',
  'save-tiktok-video-iphone': 'iPhone पर TikTok वीडियो कैसे सेव करें',
  'tiktok-video-download-android': 'Android पर TikTok वीडियो कैसे डाउनलोड करें',
  'tiktok-downloader-safe': 'क्या TikTok डाउनलोडर सुरक्षित है?',
  'tiktok-video-downloader-free': 'मुफ्त TikTok वीडियो डाउनलोडर',
  'tiktok-video-download-private': 'प्राइवेट TikTok वीडियो कैसे डाउनलोड करें',
  'tiktok-save-visible-ja': 'क्या TikTok वीडियो सेव करने पर दूसरे को पता चलता है?',
  'how-to-save-tiktok-without-watermark': 'बिना वॉटरमार्क TikTok वीडियो कैसे सेव करें',
  'tiktok-video-downloader-2026': 'TikTok वीडियो डाउनलोडर 2026',
  'tiktok-video-link-download': 'लिंक से TikTok वीडियो डाउनलोड करें',
  'telegram-video-download': 'Telegram वीडियो कैसे डाउनलोड करें',
  'telegram-video-downloader-online': 'ऑनलाइन Telegram वीडियो डाउनलोडर टूल',
  'telegram-video-save-method-ja': 'Telegram वीडियो सेव करने का तरीका',
  'telegram-video-download-pc-ja': 'PC पर Telegram वीडियो कैसे डाउनलोड करें',
  'telegram-video-download-iphone': 'iPhone पर Telegram वीडियो कैसे डाउनलोड करें',
  'telegram-video-download-android': 'Android पर Telegram वीडियो कैसे डाउनलोड करें',
  'telegram-private-video-download': 'प्राइवेट Telegram वीडियो कैसे डाउनलोड करें',
  'telegram-video-download-link': 'लिंक से Telegram वीडियो कैसे डाउनलोड करें',
  'telegram-save-visible-ja': 'क्या Telegram वीडियो सेव करने पर दूसरे को पता चलता है?',
  'telegram-video-download-bot-safe': 'क्या Telegram वीडियो डाउनलोड बॉट सुरक्षित है?',
  'best-twitter-video-downloader-2026': 'साल 2026 का सबसे अच्छा Twitter वीडियो डाउनलोडर',
  'best-tiktok-downloader-without-watermark': 'सबसे अच्छा बिना वॉटरमार्क TikTok डाउनलोडर कौन सा है',
  'safest-video-downloader-sites': 'सबसे सुरक्षित वीडियो डाउनलोडर साइटें',
  'twitter-video-downloader-not-working': 'Twitter वीडियो डाउनलोडर काम नहीं कर रहा',
  'tiktok-downloader-not-working': 'TikTok डाउनलोडर काम नहीं कर रहा',
  'telegram-video-download-not-working': 'Telegram वीडियो डाउनलोड काम नहीं कर रहा',
  'is-video-downloader-legal': 'क्या वीडियो डाउनलोडर इस्तेमाल करना कानूनी है?',
  'video-downloader-safe-or-not': 'क्या वीडियो डाउनलोडर सच में सुरक्षित है?',
  'free-video-downloader-online-comparison': 'मुफ्त ऑनलाइन वीडियो डाउनलोडर तुलना',
  'top-5-video-downloader-tools': 'top 5 वीडियो डाउनलोडर टूल',
};


const keywordJaBySlug: Record<string, string> = {
  'how-to-download-twitter-videos': 'Twitter動画の保存方法',
  'twitter-video-downloader-online-free': 'Twitter動画を保存できる無料サイト',
  'twitter-video-download-iphone': 'iPhoneでTwitter動画を保存する方法',
  'twitter-video-save-method-ja': 'Twitter 動画 保存 方法',
  'twitter-video-save-not-working-ja': 'Twitter 動画 保存 できない',
  'twitter-video-download-android': 'AndroidでTwitter動画を保存する方法',
  'twitter-gif-download': 'Twitter GIF 保存 方法',
  'twitter-video-downloader-safe': 'Twitter動画保存サイトは安全か',
  'twitter-video-download-no-watermark': 'Twitter動画を透かしなしで保存する方法',
  'twitter-video-download-mp4': 'Twitter動画をMP4で保存する方法',
  'twitter-video-download-chrome': 'ChromeでTwitter動画を保存する方法',
  'twitter-save-visible-ja': 'Twitter 保存 ばれる？',
  'twitter-video-download-private-account': '非公開アカウントのTwitter動画は保存できるか',
  'twitter-video-download-without-login': 'ログインなしでTwitter動画を保存する方法',
  'twitter-video-downloader-2026': 'Twitter動画保存サイト 2026',
  'tiktok-video-download-no-watermark': 'TikTok動画を透かしなしで保存する方法',
  'tiktok-downloader-without-watermark-online': '透かしなしTikTok動画保存サイト',
  'tiktok-video-save-method-ja': 'TikTok 動画 保存 方法',
  'tiktok-video-save-not-working-ja': 'TikTok 動画 保存 できない',
  'download-tiktok-video-hd': 'TikTok動画をHDで保存する方法',
  'tiktok-download-mp4': 'TikTok動画をMP4で保存する方法',
  'save-tiktok-video-iphone': 'iPhoneでTikTok動画を保存する方法',
  'tiktok-video-download-android': 'AndroidでTikTok動画を保存する方法',
  'tiktok-downloader-safe': 'TikTok保存サイトは安全か',
  'tiktok-video-downloader-free': '無料のTikTok動画保存サイト',
  'tiktok-video-download-private': '非公開TikTok動画は保存できるか',
  'tiktok-save-visible-ja': 'TikTok 保存 バレる？',
  'how-to-save-tiktok-without-watermark': 'TikTok動画を透かしなしで保存する方法',
  'tiktok-video-downloader-2026': 'TikTok動画保存サイト 2026',
  'tiktok-video-link-download': 'リンクからTikTok動画を保存する方法',
  'telegram-video-download': 'Telegram動画を保存する方法',
  'telegram-video-downloader-online': 'Telegram動画を保存できるサイト',
  'telegram-video-save-method-ja': 'Telegram 動画 保存 方法',
  'telegram-video-download-pc-ja': 'PCでTelegram動画を保存する方法',
  'telegram-video-download-iphone': 'iPhoneでTelegram動画を保存する方法',
  'telegram-video-download-android': 'AndroidでTelegram動画を保存する方法',
  'telegram-private-video-download': '非公開Telegram動画は保存できるか',
  'telegram-video-download-link': 'リンクからTelegram動画を保存する方法',
  'telegram-save-visible-ja': 'Telegram 保存 バレる？',
  'telegram-video-download-bot-safe': 'Telegram動画保存ボットは安全か',
  'best-twitter-video-downloader-2026': 'おすすめのTwitter動画保存サイト 2026',
  'best-tiktok-downloader-without-watermark': 'おすすめの透かしなしTikTok保存サイト',
  'safest-video-downloader-sites': '安全性で選ぶ動画保存サイト',
  'twitter-video-downloader-not-working': 'Twitter動画保存サイトが動かないときの対処法',
  'tiktok-downloader-not-working': 'TikTok保存サイトが動かないときの対処法',
  'telegram-video-download-not-working': 'Telegram動画保存ができないときの対処法',
  'is-video-downloader-legal': '動画保存サイトの利用は違法か',
  'video-downloader-safe-or-not': '動画保存サイトは安全か',
  'free-video-downloader-online-comparison': '無料動画保存サイトの比較',
  'top-5-video-downloader-tools': '動画保存サイトおすすめ5選',
};

const keywordPtBySlug: Record<string, string> = {
  'how-to-download-twitter-videos': 'como baixar vídeos do Twitter',
  'twitter-video-downloader-online-free': 'baixador de vídeos do Twitter online grátis',
  'twitter-video-download-iphone': 'como baixar vídeo do Twitter no iPhone',
  'twitter-video-save-method-ja': 'como salvar vídeos do Twitter',
  'twitter-video-save-not-working-ja': 'o vídeo do Twitter não baixa',
  'twitter-video-download-android': 'como baixar vídeo do Twitter no Android',
  'twitter-gif-download': 'como baixar GIF do Twitter',
  'twitter-video-downloader-safe': 'baixador de vídeos do Twitter é seguro',
  'twitter-video-download-no-watermark': 'baixar vídeo do Twitter sem marca d’água',
  'twitter-video-download-mp4': 'baixar vídeo do Twitter em MP4',
  'twitter-video-download-chrome': 'baixar vídeo do Twitter no Chrome',
  'twitter-save-visible-ja': 'salvar vídeo do Twitter notifica alguém?',
  'twitter-video-download-private-account': 'baixar vídeo do Twitter de conta privada',
  'twitter-video-download-without-login': 'baixar vídeo do Twitter sem login',
  'twitter-video-downloader-2026': 'baixador de vídeos do Twitter 2026',
  'tiktok-video-download-no-watermark': 'baixar vídeo do TikTok sem marca d’água',
  'tiktok-downloader-without-watermark-online': 'baixador do TikTok sem marca d’água online',
  'tiktok-video-save-method-ja': 'como salvar vídeos do TikTok',
  'tiktok-video-save-not-working-ja': 'o vídeo do TikTok não baixa',
  'download-tiktok-video-hd': 'baixar vídeo do TikTok em HD',
  'tiktok-download-mp4': 'baixar vídeo do TikTok em MP4',
  'save-tiktok-video-iphone': 'como salvar vídeo do TikTok no iPhone',
  'tiktok-video-download-android': 'como baixar vídeo do TikTok no Android',
  'tiktok-downloader-safe': 'baixador do TikTok é seguro',
  'tiktok-video-downloader-free': 'baixador de vídeos do TikTok grátis',
  'tiktok-video-download-private': 'baixar vídeo do TikTok privado',
  'tiktok-save-visible-ja': 'salvar vídeo do TikTok notifica alguém?',
  'how-to-save-tiktok-without-watermark': 'como salvar vídeo do TikTok sem marca d’água',
  'tiktok-video-downloader-2026': 'baixador de vídeos do TikTok 2026',
  'tiktok-video-link-download': 'baixar vídeo do TikTok por link',
  'telegram-video-download': 'baixar vídeo do Telegram',
  'telegram-video-downloader-online': 'baixador de vídeos do Telegram online',
  'telegram-video-save-method-ja': 'como salvar vídeos do Telegram',
  'telegram-video-download-pc-ja': 'baixar vídeo do Telegram no PC',
  'telegram-video-download-iphone': 'baixar vídeo do Telegram no iPhone',
  'telegram-video-download-android': 'baixar vídeo do Telegram no Android',
  'telegram-private-video-download': 'baixar vídeo privado do Telegram',
  'telegram-video-download-link': 'baixar vídeo do Telegram por link',
  'telegram-save-visible-ja': 'salvar vídeo do Telegram notifica alguém?',
  'telegram-video-download-bot-safe': 'é seguro usar bot para baixar vídeo do Telegram?',
  'best-twitter-video-downloader-2026': 'melhor baixador de vídeos do Twitter 2026',
  'best-tiktok-downloader-without-watermark': 'melhor baixador do TikTok sem marca d’água',
  'safest-video-downloader-sites': 'sites mais seguros para baixar vídeos',
  'twitter-video-downloader-not-working': 'baixador de vídeos do Twitter não funciona',
  'tiktok-downloader-not-working': 'baixador do TikTok não funciona',
  'telegram-video-download-not-working': 'o download de vídeo do Telegram não funciona',
  'is-video-downloader-legal': 'usar baixador de vídeos é legal?',
  'video-downloader-safe-or-not': 'baixador de vídeos é seguro ou não?',
  'free-video-downloader-online-comparison': 'comparação de baixadores de vídeo online grátis',
  'top-5-video-downloader-tools': 'top 5 ferramentas para baixar vídeos',
};
export const keywordArticles: KeywordArticle[] = baseArticles.map((a) => ({
  slug: a.slug,
  category: a.category,
  keyword: {
    en: a.en,
    es: localizeKeyword(a.en, 'es'),
    ar: localizeKeyword(a.en, 'ar'),
    ja: keywordJaBySlug[a.slug] ?? a.en,
    pt: keywordPtBySlug[a.slug] ?? a.en,
    fr: keywordFrBySlug[a.slug] ?? a.en,
    de: keywordDeBySlug[a.slug] ?? a.en,
    tr: keywordTrBySlug[a.slug] ?? a.en,
    id: keywordIdBySlug[a.slug] ?? a.en,
    hi: keywordHiBySlug[a.slug] ?? a.en,
  },
  toolPath: a.toolPath,
  supportPath: a.supportPath,
}));

export function getKeywordArticle(slug: string): KeywordArticle | undefined {
  return keywordArticles.find((a) => a.slug === slug);
}

export function getRelatedKeywordArticles(slug: string, category: KeywordCategory, limit = 3): KeywordArticle[] {
  return keywordArticles.filter((a) => a.category === category && a.slug !== slug).slice(0, limit);
}